### ISSUE TITLE
HTTP interface for Remote Transceiver

### ISSUE THREAD

**Issue by hhenry01** [UBCSailbot/network_systems#17]
### Purpose

Determine ideal library for HTTP client/server.

### Description

The Remote Transceiver needs an HTTP interface to access data sent from our onboard computer and send new global waypoint data to it.
Requirements:
- POST server endpoint to receive new data from the boat
- Client POST support to send data to the boat

### Resources

- https://github.com/yhirose/cpp-httplib looks promising

**Comment by samdai01** [comment]
Found a potentially better library that seems to have more documentation/support: 

https://github.com/pocoproject/poco

Only issue is that it may be a bit overkill but could open up lots more opportunities for expansion with new features.
